### ISSUE TITLE
Wrong type for method Del when initialize Redis Store

### ISSUE THREAD

**Issue by Yosafat1997** [eko/gocache#12]
I want to implement a chained cache with Redis and BigCache. I don't have problem to declare Bigcache store, but have problem with redis. I using redis from "github.com/go-redis/redis", gocache store and gocache cache

this is how i declare my cache:
```
var LocationCache *cache.ChainCache

func createCache(host string) *cache.ChainCache {
	redisClient := redis.NewClient(&redis.Options{Addr: host})
	bigcacheClient, _ := bigcache.NewBigCache(bigcache.DefaultConfig(720 * time.Hour))
	bigcacheStorage := store.NewBigcache(bigcacheClient, nil)
	redisStorage := store.NewRedis(redisClient, nil)

	LocationCache = cache.NewChain(
		cache.New(bigcacheStorage),
		cache.New(redisStorage))
	return LocationCache
}
```

But it give me this error:  cannot use redisClient (variable of type *redis.Client) as store.RedisClientInterface value in argument to store.NewRedis: wrong type for method Del"

Is anyone can help me? Thanks

**Comment by eko** [comment]
Hi @Yosafat1997,

I think it is because I used the latest version of the https://github.com/go-redis/redis library.

Indeed, could you move your import to the v7:

```go
import "github.com/go-redis/redis/v7"
```

This way, the following `Del` method:

https://github.com/go-redis/redis/blob/master/commands.go#L61

should match the specified interface in the Gocache library:

https://github.com/eko/gocache/blob/master/store/redis.go#L15

I hope it helps. Please close this issue if it is fixed, elsewhere I will have a closer look as soon as possible.

Thank you

**Comment by Yosafat1997** [comment]
oh okay,but if you don't mind, is there any possibilities to update this library to follow latest version of its dependencies, such as redis and all caches type that covered by this library?

**Comment by eko** [comment]
Yep, this is the latest version actually, I think you could also try with master branch instead of latest v7 tag:

```
$ go get github.com/go-redis/redis@master
```

**Comment by Yosafat1997** [comment]
Oh sorry my mistake... i mean if you want to update this library in future.

**Comment by eko** [comment]
I prefer to be based on semantic versioning and so use the v7 release tags, I will update it in case on new releases :)

Thank you for reporting this feedback!
